---
title: Stackbit Fresh Theme
baseURL: "/"
params:
  layout_style: overflow
  palette: orange
  header:
    title: Consulting Services
    tagline: IT Consulting, Process Improvement & Change Management
    profile_img: "/images/avatar-1.png"
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
